/* Main.c file generated by New Project wizard
 *
 * Created:   Thu Mar 12 2026
 * Processor: PIC16F877A
 * Compiler:  MPLAB XC8
 */

#include <xc.h>

#pragma config FOSC = XT
#pragma config WDTE = OFF
#pragma config PWRTE = ON
#pragma config BOREN = ON
#pragma config LVP = OFF
#pragma config CPD = OFF
#pragma config WRT = OFF
#pragma config CP = OFF

#define _XTAL_FREQ 4000000

void main(void)
 {
   // Write your code here
   TRISB = 0x01;
   TRISC = 0x00;
   TRISD = 0x0F;
    
    
   INTEDG = 1;
   INTE = 1;
   INTF = 0;
   GIE = 1;
   PORTC = 0x00;    
   while (1)
      ;
 }

void interrupt ISR() {
     GIE = 0;
     unsigned char key;

    if(INTF) {
       key = PORTD & 0x0F;
       switch(key){
                case 0x00: PORTC = 0x01; break;
                case 0x01: PORTC = 0x02; break;
                case 0x02: PORTC = 0x03; break;
                case 0x04: PORTC = 0x04; break;
                case 0x05: PORTC = 0x05; break;
                case 0x06: PORTC = 0x06; break;
                case 0x08: PORTC = 0x07; break;
                case 0x09: PORTC = 0x08; break;
                case 0x0A: PORTC = 0x09; break;
                case 0x0C: PORTC = 0x00; break;
                case 0x0D: PORTC = 0x00; break;
                case 0x0E: PORTC = 0x00; break;
            }
       INTF = 0;
    }
    GIE = 1;
}