/* Main.c file generated by New Project wizard
 *
 * Created:   Thu Mar 12 2026
 * Processor: PIC16F877A
 * Compiler:  MPLAB XC8
 */

#include <xc.h>

#pragma config FOSC = XT
#pragma config WDTE = OFF
#pragma config PWRTE = ON
#pragma config BOREN = ON
#pragma config LVP = OFF
#pragma config CPD = OFF
#pragma config WRT = OFF
#pragma config CP = OFF

#define _XTAL_FREQ 4000000

volatile int count_flag = 0; 

void delay_1s() {
    int overflows = 0;
    while (overflows < 122) { 
        if (count_flag == 1) {
            count_flag = 0; 
            overflows++;    
        }
    }
}

void interrupt ISR() {
    GIE = 0; // disables all unmasked interrupts to prevent interrupt overlap
    
    // RB0/INT External Interrupt
    if(INTF) { 
        unsigned char key = PORTD & 0x0F;
        switch(key){
            case 0x00: PORTC = 0x01; break;
            case 0x01: PORTC = 0x02; break;
            case 0x02: PORTC = 0x03; break;
            case 0x04: PORTC = 0x04; break;
            case 0x05: PORTC = 0x05; break;
            case 0x06: PORTC = 0x06; break;
            case 0x08: PORTC = 0x07; break;
            case 0x09: PORTC = 0x08; break;
            case 0x0A: PORTC = 0x09; break;
            case 0x0C: PORTC = 0x00; break;
            case 0x0D: PORTC = 0x00; break;
            case 0x0E: PORTC = 0x00; break;
        }
        INTF = 0; 
    }
    
    // Timer0 Overflow Interrupt
    if(TMR0IF) { 
        TMR0IF = 0; 
        count_flag = 1; 
    }
    
    GIE = 1; // enable interrupts again
}

void main(void) {
    ADCON1 = 0x06; // Configure PORTA as digital I/O
    TRISA = 0x00;  // Set PORTA as output for the LED on RA0
    TRISB = 0x01;  // RB0 as input for external interrupt
    TRISC = 0x00;  // PORTC as output for 7-segment
    TRISD = 0x0F;  // PORTD lower nibble as input for Keypad
    
    PORTA = 0x00;  
    PORTC = 0x00;  
    
    // --- CORRECTED CONFIGURATION ---
    OPTION_REGbits.INTEDG = 1; // Set external interrupt at rising edge
    
    // Configure Timer0 without overwriting INTEDG
    OPTION_REGbits.T0CS = 0;   // Internal instruction cycle clock
    OPTION_REGbits.PSA = 0;    // Prescaler assignment to TMR0
    OPTION_REGbits.PS2 = 1;    // Prescaler 1:32 (100)
    OPTION_REGbits.PS1 = 0;
    OPTION_REGbits.PS0 = 0;
    
    INTE = 1;      // enable RB0/INT external interrupt
    INTF = 0;      // clears the interrupt flag
    
    TMR0IE = 1;    // enable Timer0 overflow interrupt
    TMR0IF = 0;    // clears the interrupt flag
    
    GIE = 1;       // enables all unmasked interrupt
    
    while (1) {
        PORTAbits.RA0 = ~PORTAbits.RA0; // Toggle the LED on RA0
        delay_1s();                     // Wait for 1 second
    }
}